/* Continuação da trilha do zero absoluto. Módulos 6 a 11. */
window.ZERO_MODULOS.push(
{
 nome:"6 · Repetir sem fazer tudo à mão", descricao:"Aprender laços com passos pequenos.", aulas:[
["Por que repetir?","Repetir é realizar uma ação várias vezes. Um programa pode contar automaticamente em vez de repetir linhas copiadas.","Para dizer 'bom dia' cinco vezes, não precisamos escrever cinco comandos separados.","Repetições também são chamadas de laços ou loops.","Qual vantagem de um laço?",["Evitar tarefas repetidas.","Apagar todas as variáveis.","Mudar a cor do celular."],0,"Um laço permite executar uma instrução diversas vezes.","Pense em fazer a mesma coisa 5 vezes."],
["O primeiro for","for percorre uma sequência. Com range(3), o Python faz três voltas: 0, 1 e 2.","for numero in range(3): e abaixo print(numero) mostra 0, 1, 2.","O nome numero muda a cada volta. range(3) não começa em 1.","Quantas vezes for x in range(3) repete?",["2","3","4"],1,"Os valores são 0, 1 e 2: três voltas.","Conte do zero até dois.",{codigo:"for numero in range(3):\n    print(numero)",desafio:"Crie um for com range(2) para mostrar 'Oi' duas vezes.",regras:["for ","range(2)",":","print(","Oi"]}],
["O que é contador?","Um contador registra quantas vezes algo aconteceu.","No trabalho, cada entrada pode aumentar uma contagem: 0, 1, 2, 3...","Contadores são úteis para passos, pessoas, pontos e produtos.","Se entraram 2 pessoas e entra mais 1, o contador fica em...",["1","2","3"],2,"Somamos uma entrada: 2 + 1 = 3.","O contador aumenta em uma unidade."],
["Quando usar while?","while significa 'enquanto'. Repete enquanto uma condição é verdadeira.","Enquanto a fila tiver pessoas, atender a próxima.","Cuidado: se a condição nunca mudar, o laço pode repetir sem parar.","Enquanto significa...",["Repetir se a condição continuar verdadeira.","Executar uma única vez sempre.","Parar antes de começar."],0,"while depende da condição.","Pense em 'enquanto houver trabalho'."],
["Como parar um laço?","Um laço precisa ter uma condição de término ou outra forma de parar. break pode interromper um laço.","Se encontramos o objeto procurado, podemos parar a busca.","Planejar a parada evita repetições sem fim.","O que pode acontecer se while nunca ficar falso?",["Ele poderá repetir indefinidamente.","O aplicativo vira um jogo.","O programa soma números automaticamente."],0,"Uma condição sem saída pode causar um loop infinito.","Quando termina uma tarefa repetitiva?"],
["Exemplo: passos diários","Imagine um contador que começa em zero e recebe um novo passo a cada movimento. A cada passo, o total aumenta.","Início 0 → detectou passo → 1 → detectou outro → 2.","Na prática um sensor fornece os eventos, e o programa atualiza a contagem.","Se o contador estava em 6 e chegaram mais 2 passos, fica...",["4","8","12"],1,"6 + 2 = 8 passos.","Some duas novas unidades ao total."],
]},
{
 nome:"7 · Organizar informações", descricao:"Listas, funções e código mais fácil de manter.", aulas:[
["O que é uma lista?","Lista é uma coleção de itens guardados juntos.","compras = ['pão', 'leite', 'arroz'] guarda três produtos.","Podemos organizar nomes, notas, compras e outras informações.","O que representa ['Ana', 'Bia']?",["Dois nomes em uma lista.","Um número decimal.","Um comando de desligar."],0,"Colchetes podem agrupar itens de uma lista.","Veja os dois nomes juntos."],
["Como localizar um item?","Em Python, o primeiro item de uma lista tem posição (índice) 0, não 1.","cores = ['azul', 'verde']; cores[0] é 'azul'.","Esse detalhe parece estranho no começo, mas você vai praticar.","Qual é o primeiro índice de uma lista Python?",["1","0","2"],1,"Os índices começam em 0.","É a primeira posição, mas numerada como zero."],
["Acrescentar um item","append adiciona um item ao final da lista.","frutas = ['maçã']; frutas.append('banana') deixa duas frutas.","Não precisa recriar a lista inteira para adicionar um item.","O que faz append?",["Adiciona item à lista.","Reinicia o computador.","Transforma texto em áudio."],0,"append insere um novo item no final.","Pense em anexar mais um objeto.",{codigo:"compras = ['pão']\ncompras.append('leite')\nprint(compras)",desafio:"Crie lista frutas e acrescente 'uva' com append.",regras:["frutas","append(","uva"]}],
["Dicionário é etiqueta + valor","Dicionários guardam informações com nomes de campos (chaves).","pessoa = {'nome': 'Ana', 'idade': 12}","É como uma ficha com o campo nome e o campo idade.","Qual estrutura combina campos nome e idade?",["Dicionário.","Multiplicação.","Laço infinito."],0,"O dicionário organiza pares de chave e valor.","Imagine uma ficha de cadastro."],
["Por que criar funções?","Função é um conjunto de instruções que recebe um nome para ser usado novamente.","Uma função 'saudar' pode mostrar 'Olá' sempre que você chamá-la.","Assim você evita repetir o mesmo bloco de código em vários lugares.","Qual vantagem de funções?",["Reutilizar uma tarefa com um nome.","Fazer todos os erros desaparecerem.","Impedir qualquer mudança."],0,"Uma função agrupa instruções reutilizáveis.","Pense em uma receita que tem nome."],
["Criando uma função","Em Python, def inicia a definição de uma função. Depois colocamos o nome e os parênteses.","def saudar(): e na linha seguinte, recuada, print('Olá'). Depois chamamos saudar().","Definir a função não significa executá-la imediatamente. Precisamos chamá-la.","O que indica def em Python?",["Que estamos definindo uma função.","Que começa uma conta de dividir.","Que vamos mudar o tema."],0,"def define funções.","Lembre de 'definir'.",{codigo:"def saudar():\n    print('Olá')\nsaudar()",desafio:"Defina uma função chamada avisar que mostre 'Atenção' e depois chame avisar().",regras:["def avisar()",":","print(","Atenção","avisar()"]}],
["O que é parâmetro?","Parâmetro é uma informação que a função recebe para personalizar o trabalho.","def saudar(nome): print('Olá', nome). Se chamar saudar('Bia'), ela usa Bia.","Um parâmetro permite reutilizar a mesma função com dados diferentes.","O que muda entre saudar('Ana') e saudar('Bia')?",["O nome enviado à função.","A linguagem usada.","A versão do computador."],0,"O argumento muda, mas a função pode ser a mesma.","Veja os dois nomes diferentes."],
["Corrigir um erro aos poucos","Depurar é investigar por que o código não fez o esperado.","Leia a mensagem de erro, confira a linha, teste uma correção e execute de novo.","Evite mudar dez coisas ao mesmo tempo: fica difícil saber o que resolveu.","Qual atitude ajuda a depurar?",["Mudar tudo sem ler.","Ler a mensagem e testar uma alteração.","Ignorar o problema."],1,"Investigar um passo de cada vez facilita achar a causa.","Não adivinhe: procure pistas."],
]},
{
 nome:"8 · Criar páginas e aplicativos", descricao:"Entender a estrutura da web antes dos projetos.", aulas:[
["O que é internet?","Internet é uma rede que conecta dispositivos. Um site normalmente é entregue ao navegador por um servidor.","Seu celular pede a página e recebe arquivos para mostrar.","Mesmo um app que funciona offline pode usar a internet para atualizar dados.","O que o navegador pode receber do servidor?",["Arquivos da página.","Apenas comandos de teclado.","Somente fotos da câmera."],0,"O navegador recebe recursos como HTML, CSS e JavaScript.","Como uma encomenda de arquivos."],
["O que é HTML?","HTML organiza o conteúdo de uma página: títulos, textos, botões e listas.","<h1>Olá</h1> representa um título principal.","HTML define estrutura, não é a mesma coisa que um programa Python.","Qual linguagem estrutura uma página?",["HTML.","SQL.","Python sozinho."],0,"HTML descreve os elementos da página.","Pense no esqueleto de uma página.",{codigo:"<h1>Minha página</h1>",desafio:"Escreva um título h1 com as palavras Meu primeiro site.",regras:["<h1>","Meu primeiro site","</h1>"]}],
["O que é CSS?","CSS define a aparência dos elementos: cores, fontes, espaçamento e tamanhos.","h1 { color: blue; } deixa um título azul.","HTML diz o que é, CSS diz como parece.","Qual linguagem muda a aparência de uma página?",["CSS.","SQL.","Git."],0,"CSS é usado para apresentação e estilo.","Pense em pintar a casa depois de construir."],
["O que é JavaScript?","JavaScript pode dar comportamento à página: responder a cliques, verificar dados e atualizar conteúdo.","Ao tocar em um botão, JavaScript pode mudar uma mensagem na tela.","No navegador, HTML, CSS e JavaScript costumam trabalhar juntos.","O que JavaScript acrescenta à página?",["Interações e lógica.","Eletricidade à tomada.","Memória física ao celular."],0,"JavaScript executa comportamentos na web.","É a parte que reage às ações."],
["O que é um formulário?","Formulário é uma parte da tela em que a pessoa informa dados, como nome ou e-mail.","Uma tela de cadastro pergunta o nome e recebe a resposta.","Depois o programa deve verificar os dados e tratá-los com cuidado.","Qual exemplo é um formulário?",["Campo para digitar nome.","Apenas uma figura.","Uma parede pintada."],0,"Formulários recebem informações do usuário.","Você digita algo ali."],
["Conexão com APIs","API é um conjunto de regras para um programa pedir serviços ou dados a outro.","Um app de clima pode solicitar a temperatura a um serviço externo.","A API funciona como um atendente que leva um pedido e traz uma resposta.","Para que serve uma API?",["Para programas se comunicarem de modo definido.","Para aumentar o tamanho do celular.","Para guardar somente fotos."],0,"APIs oferecem interfaces de comunicação entre sistemas.","Pense num pedido e numa resposta."],
["O que é aplicativo mobile?","Um app mobile roda em celular ou tablet. Pode ser criado com tecnologias diferentes.","Um app de corrida pode usar tela, sensores de movimento e localização.","Alguns apps dependem da internet; outros continuam funcionando offline.","Um aplicativo mobile roda principalmente...",["Em celular ou tablet.","Somente em impressora.","Somente em televisão antiga."],0,"Mobile se refere a dispositivos móveis.","A palavra mobile lembra mobilidade."],
]},
{
 nome:"9 · Dados, segurança e trabalho em equipe", descricao:"Fundamentos para desenvolver sistemas confiáveis.", aulas:[
["Por que salvar dados?","Sem armazenamento, informações podem desaparecer quando um programa fecha.","Um app de tarefas precisa lembrar quais tarefas já foram feitas.","Salvar dados é diferente de apenas mostrar uma mensagem.","Por que um app precisa guardar informações?",["Para lembrar depois.","Para gastar mais bateria obrigatoriamente.","Para deixar o texto sempre azul."],0,"Persistência mantém dados para uso futuro.","O que acontece ao fechar o app?"],
["O que é banco de dados?","Banco de dados é um sistema organizado para armazenar e consultar informações.","Uma tabela de produtos pode ter colunas nome, preço e quantidade.","Grandes aplicativos usam bancos de dados para administrar informações.","O que um banco de dados guarda?",["Informações organizadas.","Somente cabos.","Somente imagens de fundo."],0,"Banco de dados guarda informações de forma estruturada.","É como um armário de fichas."],
["O que é SQL?","SQL é uma linguagem muito usada para consultar e modificar dados em bancos relacionais.","SELECT nome FROM produtos; pede os nomes dos produtos.","Você vai aprofundar SQL e modelagem no curso completo.","Para que serve SELECT?",["Buscar dados.","Trocar a tela do celular.","Aumentar o brilho do monitor."],0,"SELECT é usado para consultar dados.","Select significa selecionar."],
["Para que serve Git?","Git registra versões de arquivos de um projeto. Assim podemos acompanhar alterações.","Se uma mudança causar problema, o histórico ajuda a investigar versões anteriores.","O GitHub é uma plataforma que hospeda repositórios Git e facilita colaboração.","Git ajuda principalmente a...",["Controlar versões do código.","Dobrar a memória RAM.","Desligar a internet."],0,"Git mantém histórico das mudanças.","Pense em versões de um documento."],
["O que é um teste?","Um teste verifica se uma função ou parte do sistema está fazendo o que deveria.","Se uma calculadora soma 2 + 2, você pode verificar se retorna 4.","Testes não substituem completamente usar o aplicativo de verdade.","Por que testamos programas?",["Para descobrir erros antes de usar ou publicar.","Para deixar tudo mais demorado sem motivo.","Para esconder problemas."],0,"Testar ajuda a verificar comportamento esperado.","É uma conferência."],
["Segurança básica","Programas lidam com dados das pessoas. Não devemos publicar senhas, tokens privados ou informações pessoais.","Uma chave secreta não deve ficar exposta num repositório público.","É importante limitar acessos e validar entradas do usuário.","O que deve ficar protegido?",["Senha e chaves privadas.","Título de uma aula pública.","Cor de um botão."],0,"Segredos e dados sensíveis exigem proteção.","O que você não gostaria de mostrar a estranhos?"],
["O que é Firebase?","Firebase reúne serviços que podem ajudar aplicativos com autenticação, banco de dados e outras funções.","Um app pode usar Firebase Authentication para login e Firestore para guardar documentos.","Você estudará a configuração prática no curso completo.","Qual é um uso possível do Firebase?",["Autenticar usuários e guardar dados.","Consertar tela quebrada.","Aumentar a velocidade do ventilador."],0,"Firebase oferece serviços para aplicativos.","É um conjunto de ferramentas em nuvem."],
["IA ajuda, mas precisamos entender","Inteligência artificial pode explicar conceitos e sugerir código, mas pode cometer erros.","Ao receber uma sugestão da IA, leia, teste e procure entender.","Aprender é construir autonomia para decidir se a resposta faz sentido.","O que fazer com um código gerado por IA?",["Testar e entender antes de confiar.","Publicar sem ler.","Considerar sempre perfeito."],0,"A responsabilidade por revisar o programa continua sendo de quem o desenvolve.","Até ferramentas úteis podem errar."],
]},
{
 nome:"10 · Projetos que fazem sentido", descricao:"Construir aos poucos e preparar a trilha avançada.", aulas:[
["Como nasce um projeto?","Um projeto começa por um problema concreto, não por centenas de recursos.","Quer contar visitantes? Comece anotando entradas e saídas.","Escolha uma tarefa pequena, faça funcionar e só depois amplie.","Qual é um bom primeiro passo?",["Resolver uma função pequena.","Criar tudo sem testar.","Ignorar o usuário."],0,"Projetos crescem de etapas pequenas.","O menor resultado útil vem primeiro."],
["Projeto 1: saudação","Vamos planejar um programa: perguntar o nome de alguém e mostrar uma saudação.","Etapas: receber nome → guardar nome → mostrar 'Olá' e o nome.","Esse projeto usa os conceitos de entrada, variável e saída.","Qual é a entrada desse programa?",["Nome digitado.","Saudação exibida.","Cor de fundo."],0,"O nome vem da pessoa que usa o programa.","Entrada = informação recebida.",{codigo:"nome = input('Nome: ')\nprint('Olá', nome)",desafio:"Crie um programa que pergunte a cidade com input e exiba 'Cidade:' junto da resposta.",regras:["cidade","input(","print(","Cidade:"]}],
["Projeto 2: contador","Um contador é um bom exercício para treinar números e variáveis.","Começar com 0. Quando chegar uma nova pessoa, aumentar para 1.","Depois você pode registrar o horário de cada entrada.","Se contador = 4 e fazemos contador = contador + 1, o novo valor é...",["3","5","4"],1,"Somamos uma unidade ao valor anterior.","4 + 1 = 5.",{codigo:"contador = 0\ncontador = contador + 1\nprint(contador)",desafio:"Comece com total = 0, some 1 a total e depois mostre total.",regras:["total = 0","total = total + 1","print("]}],
["Projeto 3: lista de tarefas","Um app de tarefas precisa permitir criar, visualizar e marcar tarefas feitas.","Primeiro desenhe três partes: campo de texto, botão de adicionar e lista.","Só depois conectamos comportamento e armazenamento.","Qual recurso é essencial?",["Adicionar e visualizar tarefas.","Tocar música obrigatoriamente.","Ter mil cores."],0,"Um projeto bom começa pelas funcionalidades centrais.","O que torna uma lista de tarefas útil?"],
["Projeto 4: controle de entradas","Um controle de entradas pode registrar quantidade, local e hora, antes de criar telas sofisticadas.","Primeiro registre: local, horário, movimento. Depois crie relatórios.","O projeto pode evoluir para banco de dados, backups e funcionamento offline.","O que vem antes de criar gráficos complexos?",["Garantir que os registros funcionem.","Apagar os registros.","Adicionar todos os efeitos visuais."],0,"A base de dados precisa estar correta antes dos relatórios.","Primeiro capture as informações."],
["Projeto 5: aplicativo de corrida","Um app de corrida une conceitos diferentes: botões, cronômetro, dados, sensores, GPS e testes.","Comece com iniciar → pausar → finalizar. Depois adicione distância e histórico.","Projetos maiores exigem prática, testes reais e revisão constante.","Qual sequência faz sentido?",["Iniciar, pausar, finalizar.","Finalizar, iniciar, esquecer.","Apagar, travar, reiniciar."],0,"O fluxo principal precisa funcionar antes de extras.","Como começa uma corrida?"],
["Quando entrar no curso completo?","Depois desta base, você pode seguir para as 96 aulas originais. Elas são mais técnicas e aprofundam assuntos diferentes.","Reveja o que ainda estiver difícil. Você não precisa correr para concluir.","Dominar significa explicar com suas palavras e resolver exercícios sem copiar a resposta.","O que mostra que você realmente aprendeu?",["Saber explicar e aplicar sem apenas copiar.","Marcar tudo como concluído sem praticar.","Não fazer perguntas."],0,"A compreensão e a prática são mais importantes do que a pressa.","Conseguir fazer sozinho vale mais que decorar."],
]},
{
 nome:"11 · Primeiros desafios de lógica", descricao:"Conectar os fundamentos a problemas reais sem pular matemática.", aulas:[
["O que são condições? Revisão","Uma condição é uma pergunta que resulta em verdadeiro ou falso.","A temperatura está maior que 30? Sim ou não.","Condicionais ajudam o programa a escolher um caminho.","Se idade = 15, idade >= 18 é...",["Verdadeiro.","Falso.","Uma letra."],1,"15 é menor que 18.","Compare os dois números."],
["O operador de resto (%)","Em Python, 7 % 2 significa 'qual é o resto de dividir 7 por 2?'. O resultado é 1.","Divida 7 objetos em pares: sobram 1.","Esse operador é útil para identificar números pares e ímpares.","Quanto é 8 % 2?",["0","1","4"],0,"Oito objetos formam quatro pares sem sobrar nenhum.","Resto não é o resultado da divisão."],
["Do decimal ao binário: primeiro passo","No dia a dia contamos na base dez. Na base dois, só usamos 0 e 1.","0 em decimal = 0 em binário; 1 = 1; 2 = 10; 3 = 11.","Não precisa escrever um algoritmo de conversão antes de entender esses exemplos.","Qual é o 2 em binário?",["11","10","2"],1,"Na base dois, 10 representa uma vez dois e zero unidades.","Observe os exemplos apresentados."],
["Convertendo quatro em binário","Para representar 4, escrevemos 100 em binário. Ele vale um grupo de quatro, zero grupos de dois e zero unidades.","Os valores das posições binárias, da direita para a esquerda, são 1, 2, 4, 8...","4 = 1×4 + 0×2 + 0×1.","Qual é o 4 em binário?",["100","10","11"],0,"100 na base dois equivale a 4 na base dez.","Veja os grupos de 4, 2 e 1."],
["Convertendo cinco em binário","Agora podemos juntar valores. O binário 101 significa 1 grupo de quatro + 0 de dois + 1 unidade.","4 + 1 = 5, então o número decimal 5 é binário 101.","É uma soma de valores das posições. Avance sem pressa.","Qual é o 5 em binário?",["110","101","100"],1,"101 equivale a 4 + 1.","Quatro mais um resulta em cinco."],
["Transformando problemas em passos","Só agora, depois de entender divisões, restos e o sistema binário, faz sentido discutir um algoritmo de conversão.","Divida por 2, anote o resto e repita com o quociente inteiro até chegar a zero. Depois leia restos de baixo para cima.","Exemplo: 6 ÷ 2 = 3, resto 0; 3 ÷ 2 = 1, resto 1; 1 ÷ 2 = 0, resto 1. Resultado: 110.","Qual é a representação binária de 6?",["111","101","110"],2,"Os restos, lidos de baixo para cima, formam 110.","Faça as divisões com calma e anote os restos."],
]}
);
