/* Código Zero — trilha do zero absoluto, parte 1.
 * Aulas pequenas, em português simples, com exemplos antes de exercícios.
 * Não depende de serviços externos e não modifica as 96 aulas avançadas.
 */
window.ZERO_MODULOS = [
{
 nome:"1 · Primeiríssimo contato", descricao:"Entender o computador antes de digitar códigos.", aulas:[
["O que é programar?","Programar é explicar para um computador, com instruções claras, o que ele deve fazer.","Imagine ensinar alguém a preparar um sanduíche: primeiro pegar o pão, depois colocar o recheio.","Se você escrever instruções para um jogo, está criando um programa.","Qual é a melhor definição de programar?",["Dar ordens claras ao computador.","Decorar números sem entender.","Usar apenas computadores caros."],0,"Programar é criar instruções para resolver tarefas.","Pense em quem dá as instruções e quem as executa."],
["O computador adivinha?","Computadores são rápidos, mas não conseguem adivinhar o que você quis dizer. Precisam de comandos específicos.","Dizer 'arrume tudo' não ajuda; dizer 'organize as caixas por número' é mais claro.","Para mostrar uma mensagem, devemos informar qual mensagem queremos mostrar.","Por que as instruções precisam ser claras?",["Porque o computador lê pensamentos.","Porque ele executa o que foi instruído.","Porque programas não aceitam palavras."],1,"Instruções vagas dão resultados errados ou insuficientes.","Ele faz o que mandamos, não o que imaginamos."],
["O que são aplicativos e sites?","Um aplicativo é um programa. Um site também pode conter programas. Ambos são feitos de instruções.","Um relógio no celular e uma página de compras têm objetivos diferentes, mas precisam de código.","No aplicativo de corridas, um comando pode iniciar a contagem do tempo.","Qual destes é um exemplo de programa?",["Um aplicativo que marca tempo.","Uma pedra.","Um caderno vazio."],0,"Aplicativos executam ações definidas por programação.","Pense no que você usa no celular."],
["Problemas pequenos","Antes de criar um programa, identifique o problema e divida-o em partes simples.","Se o problema é 'não esquecer de beber água', você pode criar uma lista de horários.","Problema → passos → execução → resultado. Isso é uma forma de planejar.","O que devemos fazer primeiro?",["Escrever um programa de 2 mil linhas.","Entender qual problema queremos resolver.","Escolher uma cor para a tela."],1,"Entender o problema evita código sem propósito.","Antes de resolver, descubra o que precisa ser resolvido."],
["A ordem importa","A sequência das instruções muda o resultado.","Para calçar sapatos, é melhor colocar as meias antes.","Pegar copo → colocar água → beber. Se trocar a ordem, pode dar errado.","Qual sequência faz sentido?",["Beber → pegar copo → colocar água.","Colocar água → beber → pegar copo.","Pegar copo → colocar água → beber."],2,"Um algoritmo também depende da ordem dos passos.","Pense na ordem real de beber água."],
["Erros ajudam a aprender","Errar não significa incapacidade. O computador mostra sinais de onde investigar.","Uma receita com a quantidade errada de sal pode ser corrigida.","Programadores testam, observam e ajustam os programas muitas vezes.","O que fazer quando um programa apresenta erro?",["Observar a mensagem e revisar os passos.","Apagar todos os arquivos imediatamente.","Desistir de programar."],0,"Corrigir e testar fazem parte da programação.","O erro pode ser uma pista."],
]},
{
 nome:"2 · Aprender a pensar em passos", descricao:"Algoritmos do cotidiano, sem símbolos complicados.", aulas:[
["O que é algoritmo?","Algoritmo é uma sequência de passos para atingir um objetivo.","Escovar os dentes: pegar escova, colocar creme, escovar, enxaguar.","Não é necessário usar Python para criar um algoritmo no papel.","Qual é um algoritmo?",["Um passo a passo para preparar café.","Uma palavra aleatória.","Um desenho sem instruções."],0,"Algoritmos existem também fora dos computadores.","É parecido com uma receita."],
["Começo, meio e fim","Todo passo a passo organizado tem um ponto de partida, ações e um final.","Começo: separar ingredientes. Meio: misturar. Fim: servir.","Em uma atividade, escreva INÍCIO, os passos e FIM.","Onde fica 'servir o café' em uma receita?",["No final.","Antes de pegar os ingredientes.","Sempre no começo."],0,"A ação de servir costuma encerrar a sequência.","Pense quando o café já está pronto."],
["A pergunta 'se'","Às vezes precisamos decidir entre duas ações conforme uma condição.","SE estiver chovendo, levar guarda-chuva. SENÃO, sair sem ele.","Uma condição é uma pergunta com resposta sim ou não.","Se estiver chovendo, qual ação faz sentido?",["Levar guarda-chuva.","Abrir a geladeira.","Ligar a televisão."],0,"Decisão significa escolher uma ação de acordo com a situação.","O que protege da chuva?"],
["Repetir uma tarefa","Alguns passos precisam acontecer várias vezes.","Lavar três pratos: pegar prato, lavar, repetir até terminar.","Na programação chamamos isso de repetição ou laço.","O que significa 'repita 3 vezes'?",["Executar uma vez.","Executar três vezes.","Nunca executar."],1,"Repetição evita escrever o mesmo passo muitas vezes.","O número 3 indica quantas vezes."],
["Entrada e saída","Entrada é a informação que o programa recebe; saída é o resultado que ele mostra.","Você digita um nome (entrada) e o celular exibe uma saudação (saída).","Perguntar idade → receber número → mostrar uma mensagem.","Quando o usuário digita o nome, isso é...",["Entrada.","Saída.","Erro."],0,"O nome entra no programa para ser usado.","Entrar = receber."],
["Escrevendo sem código","Pseudocódigo é uma maneira simples de escrever instruções com palavras. Ainda não é Python.","INÍCIO → perguntar nome → mostrar 'Olá' → FIM.","O objetivo aqui é compreender a lógica, não decorar comandos.","O que é pseudocódigo?",["Um vírus.","Um passo a passo parecido com programação.","Uma linguagem que só funciona no celular."],1,"Pseudocódigo explica a lógica antes do código real.","Pense em 'pseudo' como um rascunho de código."],
["Primeira revisão de lógica","Você já estudou ordem, decisão, repetição, entrada e saída. São ideias usadas em quase todos os programas.","Um app pergunta seu nome, escolhe uma saudação e a exibe.","Revisar ideias antes de avançar é parte da aprendizagem.","Qual combinação descreve um programa simples?",["Receber dado → decidir → mostrar resultado.","Mostrar resultado → esquecer tudo.","Adivinhar a resposta do usuário."],0,"Um programa pode receber dados, processar e responder.","Qual parte acontece antes de mostrar um resultado?"],
]},
{
 nome:"3 · Matemática sem susto", descricao:"Números básicos antes de operações de código.", aulas:[
["Números e quantidades","Os números representam quantidades. Antes de usar fórmulas, precisamos entender o que eles contam.","Três maçãs significam uma quantidade de 3.","Um programa pode contar quantas pessoas entraram em uma sala.","Você tem 2 livros e recebe 1. Quantos livros agora?",["1","2","3"],2,"2 + 1 = 3. Juntamos mais um objeto.","Conte dois dedos e acrescente mais um."],
["Somar (+)","Somar é juntar quantidades.","Você tinha 4 moedas e ganhou 2: 4 + 2 = 6.","O sinal + representa adição.","Quanto é 5 + 3?",["8","2","15"],0,"5 mais 3 é igual a 8.","Comece no 5 e conte mais três."],
["Subtrair (−)","Subtrair é retirar uma quantidade.","Você tem 7 balas e dá 2: restam 5.","7 − 2 = 5.","Quanto é 9 − 4?",["13","5","6"],1,"9 menos 4 é igual a 5.","Conte 9 e volte quatro passos."],
["Multiplicar (×)","Multiplicar é somar a mesma quantidade várias vezes.","3 grupos com 2 lápis: 2 + 2 + 2 = 6. Então 3 × 2 = 6.","Em Python, o símbolo de multiplicação será *.","Quanto é 4 × 2?",["6","8","42"],1,"4 grupos de 2 dão 8.","Some 2 quatro vezes."],
["Dividir (÷)","Dividir pode significar repartir igualmente.","6 biscoitos entre 2 pessoas: 3 para cada.","Em Python, a divisão comum usa /.","Quanto é 8 ÷ 2?",["4","6","16"],0,"Cada pessoa recebe 4 quando 8 é dividido em dois grupos iguais.","Faça dois grupos iguais com 8 itens."],
["Qual operação vem primeiro?","Em contas com várias operações, multiplicação e divisão normalmente vêm antes da soma e subtração, salvo se houver parênteses.","2 + 3 × 2 = 2 + 6 = 8, e não 10.","Parênteses mudam a ordem: (2 + 3) × 2 = 10.","Quanto é 2 + 2 × 3?",["12","8","6"],1,"Primeiro 2 × 3 = 6; depois 2 + 6 = 8.","Faça a multiplicação antes da soma."],
["Números pares e ímpares","Um número é par se podemos formar pares sem sobrar um item. Se sobra um, é ímpar.","6 tampinhas formam 3 pares. 7 tampinhas deixam 1 sobrando.","A ideia de 'sobrar' vai ajudar na próxima aula.","Qual destes números é ímpar?",["8","10","7"],2,"7 deixa uma unidade sem par.","Tente organizar cada quantidade em duplas."],
["O que é resto da divisão?","Resto é o que sobra depois de formar grupos iguais com números inteiros.","7 balas divididas em grupos de 2: formamos 3 grupos e sobra 1.","Na programação, o resto pode ser obtido com o operador %.","Qual é o resto de 9 dividido por 2?",["1","2","0"],0,"2 cabe 4 vezes no 9 (8), e sobra 1.","Forme pares com 9 objetos."],
["Números binários sem pressa","Computadores representam informações com combinações de 0 e 1. Não precisa decorar conversões agora.","No sistema binário, 0 = zero, 1 = um, 10 = dois, 11 = três.","Binário é outro jeito de escrever quantidades. Depois de dominar divisões, você poderá aprofundá-lo.","Quais símbolos aparecem no sistema binário?",["0 e 1.","Apenas 2 e 3.","Todas as letras."],0,"O sistema binário usa dois símbolos: 0 e 1.","O nome bi lembra 'dois'."],
]},
{
 nome:"4 · Meu primeiro Python", descricao:"Uma instrução de cada vez, com exemplos claros.", aulas:[
["O que é Python?","Python é uma linguagem usada para escrever programas. Cada linguagem tem suas próprias regras.","Assim como pessoas usam português para conversar, podemos usar Python para dar instruções ao computador.","Vamos começar mostrando mensagens, sem fórmulas complicadas.","Python é...",["Um tipo de cabo.","Uma linguagem de programação.","Uma marca de mouse."],1,"Python é uma linguagem de programação.","É o idioma que usaremos para escrever programas."],
["Mostrar uma mensagem","O comando print mostra um texto na tela. As aspas indicam onde começa e termina o texto.","print('Olá!') faz o programa mostrar: Olá!","Observe o parêntese de abertura, o texto entre aspas e o parêntese de fechamento.","Qual comando mostra 'Oi'?",["print('Oi')","mostrar Oi","print Oi"],0,"print('Oi') é uma instrução válida em Python.","Veja onde estão os parênteses e as aspas.",{codigo:"print('Olá!')",desafio:"Digite um print que mostre a palavra Bom dia.",regras:["print(","Bom dia",")"]}],
["Para que servem as aspas?","As aspas avisam que uma parte do código é um texto, não o nome de uma variável.","'Recife' é texto. Sem aspas, Python pode procurar uma variável chamada Recife.","Pode usar aspas simples ou duplas, desde que abra e feche corretamente.","Qual parte é um texto?",["Recife","'Recife'","123 + 4"],1,"O texto aparece entre aspas.","Procure os sinais antes e depois da palavra.",{codigo:"print('Tudo bem?')",desafio:"Mostre a palavra Estudando usando print e aspas.",regras:["print(","Estudando",")"]}],
["Uma linha de cada vez","Um programa pode ter várias instruções; elas normalmente são executadas de cima para baixo.","print('Primeira') seguido de print('Segunda') mostra as duas mensagens nessa ordem.","Agora você consegue prever o que um pequeno código faz.","Se a primeira linha mostra 'A' e a segunda mostra 'B', o que aparece primeiro?",["B","A","Nada"],1,"A primeira instrução aparece primeiro.","Leia de cima para baixo.",{codigo:"print('Bom dia')\nprint('Boa tarde')",desafio:"Escreva duas instruções print, uma com Olá e outra com Mundo.",regras:["print(","Olá","Mundo"]}],
["O que é variável?","Variável é um nome usado para guardar uma informação, como uma etiqueta numa caixa.","nome = 'Ana' guarda o texto Ana sob o nome nome.","Depois você pode usar nome sem precisar escrever Ana novamente.","O que faz nome = 'Ana'?",["Guarda o texto Ana na variável nome.","Desliga o computador.","Multiplica Ana por 2."],0,"O sinal = em Python faz uma atribuição: guarda um valor.","Pense em uma caixa com etiqueta 'nome'.",{codigo:"nome = 'Ana'\nprint(nome)",desafio:"Crie uma variável chamada cidade com o texto Recife e mostre cidade com print.",regras:["cidade","Recife","print("]}],
["Guardar números","Uma variável também pode guardar números, sem aspas.","idade = 10 guarda o número dez. Já '10' entre aspas é texto.","Números podem participar de contas.","Qual linha guarda um número para somar?",["idade = 'dez'","idade = 10","idade = '10 anos'"],1,"10 sem aspas é um valor numérico.","Qual opção mostra só o número? ",{codigo:"pontos = 5\nprint(pontos + 2)",desafio:"Crie pontos = 3 e mostre pontos com print.",regras:["pontos","3","print("]}],
["Perguntar ao usuário","input mostra uma pergunta e recebe o que a pessoa digitar. O valor recebido começa como texto.","nome = input('Qual seu nome?')","Você pode guardar a resposta numa variável e usá-la depois.","Qual comando recebe o nome digitado?",["print('Nome')","input('Qual seu nome?')","nome == 3"],1,"input permite receber uma entrada da pessoa.","É o comando que faz uma pergunta.",{codigo:"nome = input('Seu nome? ')\nprint(nome)",desafio:"Crie nome = input('Seu nome? ') e depois mostre nome.",regras:["nome","input(","print("]}],
["Mostrar variável com texto","Podemos exibir textos e variáveis juntos. A vírgula é uma forma simples.","nome = 'Lia' seguido de print('Olá', nome).","É suficiente para criar a primeira saudação personalizada.","Qual instrução mostra Olá junto com nome?",["print('Olá', nome)","print(nome = 'Olá')","input('Olá', nome)"],0,"A vírgula separa valores que print exibe.","Você quer mostrar dois itens.",{codigo:"nome = 'Lia'\nprint('Olá', nome)",desafio:"Guarde nome = 'Bia' e mostre 'Bem-vinda' junto do nome usando print.",regras:["nome","Bia","Bem-vinda","print("]}],
["Texto formatado, bem devagar","Uma f-string é uma forma de colocar o valor de uma variável dentro de um texto. É opcional no começo.","nome = 'Lia' e print(f'Olá, {nome}') mostram: Olá, Lia.","O f vem antes da aspa e {nome} indica onde inserir o valor.","Para que servem {nome} em uma f-string?",["Apagar o nome.","Inserir o valor guardado em nome.","Dividir por dois."],1,"As chaves colocam a variável dentro do texto.","Imagine trocar {nome} pelo conteúdo da caixa 'nome'."],
]},
{
 nome:"5 · Escolhas em Python", descricao:"Tomar decisões sem decorar tudo de uma vez.", aulas:[
["Comparar valores","Comparar é verificar se duas informações atendem a uma condição. O resultado pode ser verdadeiro ou falso.","5 > 3 significa '5 é maior que 3'.","Em Python, == compara igualdade. Já = guarda um valor.","Qual é verdadeira?",["2 > 8","4 == 4","3 > 9"],1,"Quatro é igual a quatro.","O símbolo == pergunta se são iguais."],
["O primeiro if","if significa 'se'. O Python só executa o bloco quando a condição é verdadeira.","idade = 12 e if idade >= 10: executa o bloco abaixo porque 12 é pelo menos 10.","A instrução dentro do if fica com um pequeno recuo, chamado indentação.","O que if verifica?",["Uma condição.","Uma cor.","Um arquivo de áudio."],0,"if permite tomar uma decisão.","Lembre de 'SE estiver chovendo...'.",{codigo:"idade = 12\nif idade >= 10:\n    print('Pode entrar')",desafio:"Escreva um if que verifique se pontos é maior que 5 e mostre 'Legal'.",regras:["if ","pontos",">","5",":","print(","Legal"]}],
["Quando não acontecer: else","else significa 'senão'. Ele oferece uma segunda ação quando o if é falso.","if chuva: levar guarda-chuva; else: sair sem guarda-chuva.","Em Python, else: vem alinhado ao if e o bloco também precisa de recuo.","Para que serve else?",["Repetir para sempre.","Executar a alternativa quando if for falso.","Guardar uma foto."],1,"else indica o caminho alternativo.","É o nosso 'senão' do cotidiano."],
["Muitas possibilidades: elif","elif representa 'senão, se...' e serve para conferir outra condição.","Se nota >= 7: aprovado. Senão, se nota >= 5: recuperação. Senão: revisar mais.","Não é necessário decorar agora; a ideia é escolher entre mais de dois caminhos.","Quando elif é útil?",["Quando há várias condições possíveis.","Para aumentar volume.","Para colocar uma imagem de fundo."],0,"elif adiciona outras verificações.","Imagine três opções para a mesma pergunta."],
["Recuos são importantes","Em Python, espaços no começo da linha mostram quais instruções pertencem a um bloco.","if 2 > 1: e na linha de baixo quatro espaços antes de print('Sim').","Os espaços não são enfeite: fazem parte da estrutura do código.","Qual linha está dentro de if?",["Uma linha recuada logo abaixo do if.","Qualquer linha do computador.","Só linhas com números."],0,"Indentação indica a quem cada instrução pertence.","Procure o recuo antes do comando."],
["Duas condições: and e or","and exige que as duas condições sejam verdadeiras. or exige que pelo menos uma seja.","Tem ingresso AND é maior de idade → entra. Tem passe OR tem convite → entra.","Use esses operadores depois de dominar if e else.","Quando 'and' permite avançar?",["Quando nenhuma condição é verdadeira.","Quando apenas uma é verdadeira.","Quando ambas são verdadeiras."],2,"and quer dizer 'e': as duas partes precisam valer.","Leia 'A e B': você precisa das duas."],
]}
];
